name: 'optim.Adam'
kwargs:
  lr: 0.05
  weight_decay: 0.000
batcher_name: MiniBatcherPerClass
batcher_kwargs:
  batch_size: 1000
  labels_per_class: 70
max_train_iters: 30000
lrsche: [[2000, .1],[5000, .1],[10000, .1]]