name: 'optim.SGD'
kwargs:
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0001
batcher_name: MiniBatcherPerClass
batcher_kwargs:
  batch_size: 1000
  labels_per_class: 80
max_train_iters: 20000
lrsche: [[1000, .1],[3000, .1],[5000, .1]]