name: 'optim.SGD'
kwargs:
  lr: 0.05
  momentum: 0.99
  weight_decay: 0.00
batcher_name: MiniBatcherPerClass
batcher_kwargs:
  batch_size: 1000
  labels_per_class: 70
  use_sup: .5
max_train_iters: 20000
lrsche: [[1000, .1],[2000, .1],[3000, .1]]