name: 'optim.SGD'
kwargs:
  lr: 0.05
  momentum: 0.9
  weight_decay: 0.0001
batcher_name: MiniBatcher
batcher_kwargs:
  batch_size: 128
max_train_iters: 20000
lrsche: [[3000, .1],[6000, .1],[9000, .1]]