name: 'optim.Adam'
kwargs:
  lr: 0.0002
  betas: [.5,0.999]
batcher_name: MiniBatcher
batcher_kwargs:
  batch_size: 64
  fraction_labelled_per_batch: 0.1
max_train_iters: 200000
lrsche: [[10000, .1],[20000, .1],[30000, .1]]